
BASEDIR = ../../..

include $(BASEDIR)/etc/buildsys/config.mk
	


LIBS_colliJoystick = stdc++ fawkescore fawkesutils fawkesinterface fawkesblackboard fawkesbaseapp fawkesconfig NavigatorInterface JoystickInterface MotorInterface
OBJS_colliJoystick = colliJoystick.o -lm  

OBJS_all    = $(OBJS_colliJoystick)	
BINS_all = $(BINDIR)/colliJoystick      

include $(BUILDSYSDIR)/base.mk
	
	

							
