
BASEDIR = ../../..

include $(BASEDIR)/etc/buildsys/config.mk
	


LIBS_colliManual = stdc++ fawkescore fawkesutils fawkesinterface fawkesblackboard fawkesbaseapp fawkesconfig NavigatorInterface
OBJS_colliManual = colliManual.o -lm  

OBJS_all    = $(OBJS_colliManual)	
BINS_all = $(BINDIR)/colliManual      

include $(BUILDSYSDIR)/base.mk
	
	

							
